export const tutorialAudioMap: Record<string, any> = {
  'login_0.mp3': require('../../assets/tutorial-audio/login_0.mp3'),
  'login_1.mp3': require('../../assets/tutorial-audio/login_1.mp3'),
  'login_2.mp3': require('../../assets/tutorial-audio/login_2.mp3'),
  'novo_cliente_0.mp3': require('../../assets/tutorial-audio/novo_cliente_0.mp3'),
  'novo_cliente_1.mp3': require('../../assets/tutorial-audio/novo_cliente_1.mp3'),
  'novo_cliente_2.mp3': require('../../assets/tutorial-audio/novo_cliente_2.mp3'),
  'novo_cliente_3.mp3': require('../../assets/tutorial-audio/novo_cliente_3.mp3'),
  'novo_cliente_4.mp3': require('../../assets/tutorial-audio/novo_cliente_4.mp3'),
  'novo_cliente_5.mp3': require('../../assets/tutorial-audio/novo_cliente_5.mp3'),
  'metas_0.mp3': require('../../assets/tutorial-audio/metas_0.mp3'),
  'metas_1.mp3': require('../../assets/tutorial-audio/metas_1.mp3'),
  'metas_2.mp3': require('../../assets/tutorial-audio/metas_2.mp3'),
  'metas_3.mp3': require('../../assets/tutorial-audio/metas_3.mp3'),
  'nova_venda_0.mp3': require('../../assets/tutorial-audio/nova_venda_0.mp3'),
  'nova_venda_1.mp3': require('../../assets/tutorial-audio/nova_venda_1.mp3'),
  'nova_venda_2.mp3': require('../../assets/tutorial-audio/nova_venda_2.mp3'),
  'nova_venda_3.mp3': require('../../assets/tutorial-audio/nova_venda_3.mp3'),
  'nova_venda_4.mp3': require('../../assets/tutorial-audio/nova_venda_4.mp3'),
  'avaliacao_0.mp3': require('../../assets/tutorial-audio/avaliacao_0.mp3'),
  'avaliacao_1.mp3': require('../../assets/tutorial-audio/avaliacao_1.mp3'),
  'avaliacao_2.mp3': require('../../assets/tutorial-audio/avaliacao_2.mp3'),
  'avaliacao_3.mp3': require('../../assets/tutorial-audio/avaliacao_3.mp3'),
  'avaliacao_4.mp3': require('../../assets/tutorial-audio/avaliacao_4.mp3'),
  'avaliacao_5.mp3': require('../../assets/tutorial-audio/avaliacao_5.mp3'),
};
